### ISSUE TITLE
Import Error: 404 Not Found

### ISSUE THREAD

**Issue by namoosshah** [eveningkid/denodb#93] opened 2020-08-11 19:11 UTC
error: Import 'https://deno.land/x/color/index.ts' failed: 404 Not Found
I am trying to use version 1.0.4 (Latest available on deno.land), but it is throwing this import error.

deno 1.2.3
v8 8.6.334
typescript 3.9.2

**Comment by eveningkid** [comment] 2020-08-11 19:33
Hey Syed,

This is a duplicate of #91.

1.0.5 was not yet available on `deno.land` because github web hooks were not activated on this project.

You should soon be able to get 1.0.5 and this should fix the issue.

Have a great day :)

**Closed by eveningkid** 2020-08-11 19:33 UTC
