### ISSUE TITLE
Getting existing record on creation

### ISSUE THREAD

**Issue by borsemayur2** [eveningkid/denodb#223] opened 2021-04-16 03:21 UTC
I get the existing record `{id:1, "user"}` on creation `await User.create({name:"user1"})` while the actual created record {id:4, name:"user1"} is shown in `User.all()` with `sqlite` db.
![image](https://user-images.githubusercontent.com/47341981/114965747-db7ed880-9e8e-11eb-80f7-23df8e751c31.png)

**Comment by stillalivx** [comment] 2021-04-16 15:02
Sorry, I don't get you. 😅
Can you show me your code and the expected result?

**Comment by borsemayur2** [comment] 2021-04-16 16:35
Here's the repo: https://github.com/borsemayur2/users-demo-oak-graphql-server

**Comment by borsemayur2** [comment] 2021-04-16 16:38
Getting existing user in `addUser` query
![image](https://user-images.githubusercontent.com/47341981/115056104-09503580-9f00-11eb-8c22-70c6d2ec82b4.png)

Getting newly created user in `users` query.
![image](https://user-images.githubusercontent.com/47341981/115056082-01909100-9f00-11eb-830a-407be29dd319.png)

**Comment by stillalivx** [comment] 2021-04-16 16:48
Okay, I think I already understand.

You have a database with, for example, 2 records... Then you add another record, you expect that the function returns the information about the last inserted record but you received the first record. 

Am I right?

**Comment by borsemayur2** [comment] 2021-04-16 17:22
> 
> 
> Okay, I think I already understand.
> 
> You have a database with, for example, 2 records... Then you add another record, you expect that the function returns the information about the last inserted record but you received the first record.
> 
> Am I right?

yes.

**Comment by eveningkid** [comment] 2021-04-16 20:51
Ok, so I dug into the issue and, in a nutshell: denodb uses Dex for building SQL queries (which is a deno version of Knex), that does not support returning ids on inserts/updates/etc.

What denodb does at the moment, is calling `.where(...)` using the given values for the insert:

```js
const user = await User.create({ name: 'Mayur' });
// 1) Insert Mayur into User
// 2) Find user where "name = Mayur"
```

This is why you're getting the wrong id when you insert a user with the same name than a previous one...because it gets the first record that matched the where query. [You can see the code for this here.](https://github.com/eveningkid/denodb/blob/master/lib/connectors/sqlite3-connector.ts#L73-L87)

There is [one way of getting it though](https://github.com/knex/knex/issues/2917#issuecomment-440263593) (using Knex), at least for single inserts because I don't think we could get the last inserted id for multiple inserts (I could be wrong). They mention `last_insert_id` but [it seems to be `last_insert_rowid()` instead](https://www.sqlite.org/lang_corefunc.html#last_insert_rowid).

To make this work, I think we need to replace [this line](https://github.com/eveningkid/denodb/blob/master/lib/connectors/sqlite3-connector.ts#L86), with:

```js
// /!\ For single records only
const lastInsertQuery = this._client.query(
  `SELECT last_insert_rowid() as last_id FROM ${queryDescription.schema.table}`,
  []
);

const lastInsertId = lastInsertQuery.last_id;
return queryDescription.schema.find(lastInsertId);
```

I haven't tested it but I think this should be something around this...

To test it:
1) create a test file with a sqlite database
2)
```js
const dummyUser = await User.create({ name: "test" });
console.log(dummyUser.id); // Should log 1
```
3)
```js
const user = await User.create({ name: "test" });
console.log(user.id); // Should log 2 (or 1 without the fix)
```

@stillalivx do you think you could have a look?

**Comment by stillalivx** [comment] 2021-04-16 20:57
@eveningkid, okay, I'm gonna make the changes and test it. If everything looks good, I'll make PR.

**Comment by eveningkid** [comment] 2021-04-16 21:05
Thanks man, I really hope this works! It is surprising SQLite is different about this...

**Comment by stillalivx** [comment] 2021-04-17 03:07
@eveningkid, We have a little problem. It seems like [this conditional](https://github.com/eveningkid/denodb/blob/d973df16a18b31e38126b596ab391373658bbd9a/lib/connectors/sqlite3-connector.ts#L78) always is true. Reading [sqlite module](https://dyedgreen.github.io/deno-sqlite/#/api?id=dblastinsertrowid)'s docs, I found that exists a property calls `lastInsertRowId`.  

I think that we could add something like:
```typescript
if (
  (queryDescription.type === "insert" ||
   queryDescription.type === "update") &&
  queryDescription.values
) {
  if (Array.isArray(queryDescription.values)) {
    if (queryDescription.values.length === 1 && 
        queryDescription.type === "insert"
    ) {
        return queryDescription.schema.find(this._client.lastInsertRowId) // Here we add  the statement
    }

    return await Promise.all(
      queryDescription.values.map((values) =>
        queryDescription.schema.where(values).first()
      ),
    );
  }

  return queryDescription.schema.find(this._client.lastInsertRowId); // Also here, but I think that is imposible to execute
}
```
Now, the problem is when something like this is execute:
```typescript
await User.create([{ name: 'test' }, {name: 'test'}, {name: 'test'}]);
```
How we could know its ids? Right know I think that we could make something like:
1. Check if we have an insert statement
2. Check if we're gonna insert multiple records
3. If we have, make a query to get the last record's id
4. Make the query (insert)
5. Then, return the records inserted after the id that we got (3)

Well, those steps could have problems... For example, if two users make the same request at the same time... It could throw unexpected results... So complicated... 

**In the other hand... We could warn that if a multiple records are inserted, the function will return the last inserted record.**

@borsemayur2, you know a way to solve this issue? Can SQLite return the inserted ids if this query is executed?
```sqlite
insert into `users` (`name`) select 'test' as `name` union all select 'test' as `name` union all select 'test' as `name`
```

**Comment by borsemayur2** [comment] 2021-04-17 03:26
> 
> 
> @eveningkid, We have a little problem. It seems like [this conditional](https://github.com/eveningkid/denodb/blob/d973df16a18b31e38126b596ab391373658bbd9a/lib/connectors/sqlite3-connector.ts#L78) always is true. Reading [sqlite module](https://dyedgreen.github.io/deno-sqlite/#/api?id=dblastinsertrowid)'s docs, I found that exists a property calls `lastInsertRowId`.
> 
> I think that we could add something like:
> 
> ```ts
> if (
>   (queryDescription.type === "insert" ||
>    queryDescription.type === "update") &&
>   queryDescription.values
> ) {
>   if (Array.isArray(queryDescription.values)) {
>     if (queryDescription.values.length === 1 && 
>         queryDescription.type === "insert"
>     ) {
>         return queryDescription.schema.find(this._client.lastInsertRowId) // Here we add  the statement
>     }
> 
>     return await Promise.all(
>       queryDescription.values.map((values) =>
>         queryDescription.schema.where(values).first()
>       ),
>     );
>   }
> 
>   return queryDescription.schema.find(this._client.lastInsertRowId); // Also here, but I think that is imposible to execute
> }
> ```
> 
> Now, the problem is when something like this is execute:
> 
> ```ts
> await User.create([{ name: 'test' }, {name: 'test'}, {name: 'test'}]);
> ```
> 
> How we could know its ids? Right know I think that we could make something like:
> 
>     1. Check if we have an insert statement
> 
>     2. Check if we're gonna insert multiple records
> 
>     3. If we have, make a query to get the last record's id
> 
>     4. Make the query (insert)
> 
>     5. Then, return the records inserted after the id that we got (3)
> 
> 
> Well, those steps could have problems... For example, if two users make the same request at the same time... It could throw unexpected results... So complicated...
> 
> **In the other hand... We could warn that if a multiple records are inserted, the function will return the last inserted record.**
> 
> @borsemayur2, you know a way to solve this issue? Can SQLite return the inserted ids if this query is executed?
> 
> ```
> insert into `users` (`name`) select 'test' as `name` union all select 'test' as `name` union all select 'test' as `name`
> ```

No

**Comment by eveningkid** [comment] 2021-04-17 22:45
@stillalivx, thank you for looking into this!

You are right about the condition that is always true...I checked and that is because when creating a record, the query builder makes it an array of insertions.

That should simplify our task actually. This is what I suggest:

```js
if (
  (queryDescription.type === "insert" ||
   queryDescription.type === "update") &&
  queryDescription.values
) {
  // Since we can't accurately get the ids except for the last record...then we shouldn't.
  // We can't do something the engine doesn't support by default I think.
  // Let's return all the given values and only fetch the last record

  const lastInsertedRecord = await queryDescription.schema.find(this._client.lastInsertRowId);  
  return queryDescription.values.slice(0, -1).concat(lastInsertedRecord);
}
```

Btw, does "lastInsertRowId" also work for updated records? If not, then we only need to do the above for insertions.
Otherwise, for updates, it should just return the `queryDescription.values`.

Now, I have an idea to fix the issue for multiple insertions. Right now, [it creates one big query](https://github.com/eveningkid/denodb/blob/d973df16a18b31e38126b596ab391373658bbd9a/lib/model.ts#L412-L430) while we could do one query for each insertion instead.

```js
const results = await Promise.all(
  insertions.map((field) => {
    return this._runQuery(
      this._currentQuery
        .table(this.table)
        .create(this.formatFieldToDatabase(field))
        .toDescription()
    );
  })
);
```

If we run X queries instead of one, then this means that `sql-connector.query` would get the `lastInsertedRowId` each time and return the right result. It's not optimal but at least this would be consistent?

You could give it a try and see if it returns the right result, by running your code again:

```js
const users = await User.create([{ name: 'test' }, {name: 'test'}, {name: 'test'}]);
```

I hope this will work :)

**Comment by stillalivx** [comment] 2021-04-17 23:24
Okay, thats a better way. Same, I will check it and if everything is okay, I'll make PR! :)
And... No, `lastInsertedRowId` just work for `insert` statements. :/

**Comment by stillalivx** [comment] 2021-04-18 15:37
Hey! @eveningkid. A few things:

1. If we apply this changes
> ```js
> const results = await Promise.all(
>   insertions.map((field) => {
>     return this._runQuery(
>       this._currentQuery
>         .table(this.table)
>         .create(this.formatFieldToDatabase(field))
>         .toDescription()
>     );
>   })
> );
> ```
`queryDescription.values` is no longer an array, but an object. So... Instead of this
> ```js
> if (
>   (queryDescription.type === "insert" ||
>    queryDescription.type === "update") &&
>   queryDescription.values
> ) {
>   // Since we can't accurately get the ids except for the last record...then we shouldn't.
>   // We can't do something the engine doesn't support by default I think.
>   // Let's return all the given values and only fetch the last record
> 
>   const lastInsertedRecord = await queryDescription.schema.find(this._client.lastInsertRowId);  
>   return queryDescription.values.slice(0, -1).concat(lastInsertedRecord);
> }
> ```
I wrote:
```js
if (
   (queryDescription.type === "insert" ||
    queryDescription.type === "update") &&
   queryDescription.values
 ) {
   if (queryDescription.type === "insert") {
       return await queryDescription.schama.find(this._client.lastInsertRowId);
   }

   return queryDescription.values;
}
```
I was wondering if is posible to implement something like `MySQLConnector.query` does. Return and object with the information about the affectedRows and if is an insertion, the last insert id. 
```js
User.create({ name: 'name1' }); // return {  affectedRows: 1, lastInsertId: 1 }
User.where({ id: 1 }).update({ name: 'name2' }); // return { affectedRows: 1 } same for delete...
```
It is possible on SQLite thanks os `SQLite.changes` property. What do you think?

**Comment by eveningkid** [comment] 2021-04-18 21:38
Hey @stillalivx,

I am not sure to understand your point about the first part. If you know what you're doing, I trust you and will wait to see your code in a PR.

For the second part, I agree this would be nice! If it's easy for you to add at the same time, please do :)

**Comment by eveningkid** [comment] 2021-04-20 23:40
Hey Mayur,

Thanks to @stillalivx you can now get the last created id:

```js
const { lastInsertId } = await User.create({ name: "Mayur" });
const user = await User.find(lastInsertId);
```

Hope this solves your issue :)

Good day and thank you for your patience

**Comment by borsemayur2** [comment] 2021-04-21 00:36
Thanks @eveningkid @stillalivx

**Comment by borsemayur2** [comment] 2021-04-26 03:14
Empty records returns `{ affectedRows: 0 }` instead of `[]` for `await User.all()`.
```
console.log(await User.all()); // returns User { affectedRows: 0 }
await User.create({ name: "abc" });
console.log(await User.all());  // returns User []
```
Not sure if its an issue. `v1.0.33` would return `[]` if no records found

![image](https://user-images.githubusercontent.com/47341981/116023875-b3e7f700-a66a-11eb-988a-c400b6adfee3.png)

**Comment by stillalivx** [comment] 2021-04-26 03:20
Okay, thanks. I'll fix it when @eveningkid merges a pending pull request.

**Comment by eveningkid** [comment] 2021-04-26 14:09
Hey @borsemayur2,

Could you please use `master` and let us know if #247 has fixed your issue?

Thanks :)

**Comment by borsemayur2** [comment] 2021-04-26 15:23
> 
> 
> Hey @borsemayur2,
> 
> Could you please use `master` and let us know if #247 has fixed your issue?
> 
> Thanks :)

Works with `master`. Thanks @eveningkid @stillalivx

**Comment by eveningkid** [comment] 2021-04-26 16:47
Great, I'll close this then :)

Thanks for confirming!

**Closed by eveningkid** 2021-04-26 16:47 UTC
