### ISSUE TITLE
Annoying type declaration errors

### ISSUE THREAD

**Issue by Danieliessen** [eveningkid/denodb#138] opened 2020-10-17 09:22 UTC
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
    export { LogLevels, LevelName } from "./levels.ts";
                        ~~~~~~~~~
        at https://deno.land/x/std@0.63.0/log/mod.ts:13:21
    
    TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
      Deferred,
      ~~~~~~~~
        at https://deno.land/x/mysql@v2.4.0/deps.ts:3:3
    
    TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
    export { Client, ClientConfig } from "./src/client.ts";
                     ~~~~~~~~~~~~
        at https://deno.land/x/mysql@v2.4.0/mod.ts:1:18

**Comment by tsaulic** [comment] 2020-11-01 11:16
Any way around this? I want to use denodb in my project. I'm not that experienced with JavaScript/TS in general, just learning, but this issue is preventing me from using the module.

**Comment by juslin03** [comment] 2020-11-03 12:33
I have the same issue with my project !

**Comment by stillalivx** [comment] 2020-11-07 01:30
#146

**Comment by eveningkid** [comment] 2020-11-11 00:23
Duplicate of #146 indeed, let's keep all the information in one place.

@Danieliessen, you'll find the answer on that other issue. In a nutshell:
1) Try reloading your dependencies, using: `deno run --reload your_script_name.ts`
2) From @stillalivx: Create a `tsconfig.json` file at the root of your project with the following:
```json
{
  "compilerOptions": {
    "isolatedModules": false
  }
}
```
Then run your code:
```bash
deno run -c tsconfig.json --allow-net --allow-read --unstable server.ts
```

Hope this will solve it for you :)

**Closed by eveningkid** 2020-11-11 00:23 UTC
