### ISSUE TITLE
Getting a error on one to many relationships, with percona server Mysql 5.7

### ISSUE THREAD

**Issue by prisis** [eveningkid/denodb#40] opened 2020-06-06 00:31 UTC
Hey :),

i just getting a error with this example https://eveningkid.github.io/denodb-docs/docs/guides/one-to-many with the percona server mysql 5.7

```
error: Uncaught Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'alter table `businesses` add constraint `businesses_ownerid_foreign` foreign key' at line 2

throw new Error(error.message);

at Connection.nextPacket (https://deno.land/x/mysql/src/connection.ts:95:17)
    at async Connection.execute (https://deno.land/x/mysql/src/connection.ts:162:19)
    at async https://deno.land/x/mysql/src/client.ts:101:14
    at async Client.useConnection (https://deno.land/x/mysql/src/client.ts:111:22)
    at async Client.execute (https://deno.land/x/mysql/src/client.ts:100:12)
    at async Function._createInDatabase (https://deno.land/x/denodb/lib/model.ts:80:5)
    at async Database.sync (https://deno.land/x/denodb/lib/database.ts:94:7)
```

Is mysql 5.7 not supported, or is it a bug?

**Comment by eveningkid** [comment] 2020-06-06 09:42
Hello Daniel,

Thanks for sharing this issue with me!

Alright so the problem is that I don't have any MySQL database to help debugging this (I never managed to install MySQL on my computer -_-, and online providers usually don't have MySQL 5.5).

From what Deno MySQL says, it only supports MySQL 5.5 so this could be the reason.

I don't really want to ask you to debug this code for me, but I'm afraid I can't help on this for now. I will add the "help wanted" label in case someone sees it too and manage to help you.

For now I would suggest to switch to PostgreSQL or play around with SQLite (postgres being a really good alternative if I'm honest).

Keep in touch, and let me know if there is anything else I could help with

**Comment by prisis** [comment] 2020-06-06 14:27
Im using docker to manager the MySQL or PostgreSQL on my computer and its working always for me :), if i have more time to check the mysql adapter, will try to find the bug than ;)

**Comment by eveningkid** [comment] 2020-06-11 09:41
Alright, hope you don't mind I close this for now then.

I really think MySQL driver for deno is too limited at the moment...

I am still waiting on an improved version but until then, MySQL users might be frustrated using deno!

Thanks for reporting the issue. I hope you had more chance playing around with denodb using other database types!

Have a good day Daniel :)

**Closed by eveningkid** 2020-06-11 09:41 UTC
Labels: help wanted

**Comment by eveningkid** [comment] 2020-06-16 23:00
Hey Daniel,

I finally managed to get MySQL 5.7 — just like yours, running on my laptop :)

I had the exact same issue and obviously decided to fix this (we're engineers after all). Here were the issues:
- the MySQL driver couldn't take multiple queries at once, I had to split them on `;` (which was a similar behaviour with SQLite)
- a foreign key was an integer, but the actual primary key it was targeting was a string. So for sure MySQL couldn't manage to link these two!
- dropping tables have to be the done in the right order, based on the foreign keys

So here's the code that is now working on my side and hopefully will on yours too! :)

```typescript
import { DataTypes, Database, Model, Relationships } from "https://deno.land/x/denodb/mod.ts";

const db = new Database({ dialect: "mysql", debug: true }, {
  host: "localhost",
  username: "root",
  password: "",
  database: "mysql",
});

class Owner extends Model {
  static table = "owners";

  static fields = {
    id: {
      type: DataTypes.STRING,
      primaryKey: true,
    },
    name: DataTypes.STRING,
  };

  static businesses() {
    return this.hasMany(Business);
  }
}

class Business extends Model {
  static table = "businesses";

  static fields = {
    id: {
      type: DataTypes.STRING,
      primaryKey: true,
    },
    name: DataTypes.STRING,
    ownerId: Relationships.belongsTo(Owner),
  };

  static owner() {
    return this.hasOne(Owner);
  }
}

db.link([Owner, Business]);

await Business.drop();
await Owner.drop();

await db.sync();

await db.close();
```

I know this comes out of nowhere but I just wanted to let you know it's now all fixed!

I hope you will give denodb another chance. Do not hesitate to raise any other issue, I now have MySQL to debug things out hehe

Keep in touch!

**Comment by prisis** [comment] 2020-06-17 10:43
Hey :), thank you for the response :)

I switched my db to arangodb and created a client for it, its fits better for my use case.

But if i start a new project i will try denodb again :)

**Comment by eveningkid** [comment] 2020-06-17 10:58
It's funny because I found the arangodb library not long ago and didn't even notice it was ported by you for Deno! :)

All good, I might even add it to denodb because it looks cool.

Take care mate

**Comment by prisis** [comment] 2020-06-17 12:13
Its this one, https://github.com/dmpjs/arangojs, i think there is a second one, didnt have time to add it to the deno database
