### ISSUE TITLE
SQLite 'Unique Index' Uncaught Error

### ISSUE THREAD

**Issue by Ericarthurc** [eveningkid/denodb#65] opened 2020-06-27 18:04 UTC
```
import { Database, DataTypes, Model } from "https://deno.land/x/denodb/mod.ts";

const db = new Database("sqlite3", {
  filepath: "./db.sqlite",
});

class User extends Model {
  static table = "users";

  static timestamps = true;

  static fields = {
    id: {
      primaryKey: true,
      autoIncrement: true,
    },
    name: DataTypes.STRING,
    email: {
      type: DataTypes.STRING,
      unique: true,
      allowNull: false,
      length: 50,
    },
  };
}

db.link([User]);
await db.sync();

await User.create([
  {
    name: "Eric",
    email: "test@me.com",
  },
]);

const person = await User.all();
console.log(person);
```

The fist time this code runs it will generate a 'db.sqlite' file in the root of the directory. And the console.log(person) will print to the console the User.all() query. If I stop the code, change the email string, and re-run it; I get an Uncaught SqliteError.

![Capture](https://user-images.githubusercontent.com/22304079/85928903-81f8df00-b865-11ea-9bbb-d1df7d1f5bd2.PNG)

The errors seems to happen on the sync() method. If I delete the database and remove the 'unique' key word, no error.

**Comment by eveningkid** [comment] 2020-06-30 17:41
Hello Eric,

I finally had time to get back to this project and look into your issue :)

So yes, this is actually an expected behaviour. `sync` will synchronise your models with your current database.

In your case, your table already exists and also already have a unique index on `users.email` (because you called `sync` once). I would recommend to separate your code into two parts: the one that initialises your database and the one that will run ever after (which doesn't need models initialisation anymore).

I hope this makes sense. Let me know if you have any other question :)

Keep in touch

**Comment by eveningkid** [comment] 2020-07-01 15:24
I will close this for now, do not hesitate to send another message if you need further help!

Have a great day

**Closed by eveningkid** 2020-07-01 15:24 UTC

**Comment by Ericarthurc** [comment] 2020-07-02 03:38
> I will close this for now, do not hesitate to send another message if you need further help!
> 
> Have a great day

thank you; I haven't had a chance yo look at it yet, but I will :D

**Comment by chovy** [comment] 2021-07-21 02:57
I don't understand. how do we fix??
