### ISSUE TITLE
Import 'https://deno.land/x/sqlite/src/db.js' failed: 404 Not Found

### ISSUE THREAD

**Issue by blogwy** [eveningkid/denodb#27] opened 2020-06-02 08:28 UTC

**Comment by eveningkid** [comment] 2020-06-02 13:12
Hey, not so sure what might be the issue there.

@dyedgreen, would you have some input on this?

Not so sure if the issue comes from the user or from the library.
I am personally facing no issue.

**Comment by dyedgreen** [comment] 2020-06-02 13:25
This looks like an issue with and old/ outdated dependency. Can you try re-running your script with the `--reload` flag to check if that's the issue. (@blogwy)

If that doesn't help could you provide a minimal example code which reproduces the error?

**Comment by blogwy** [comment] 2020-06-03 05:49
> Hey, not so sure what might be the issue there.
> 
> @dyedgreen, would you have some input on this?
> 
> Not so sure if the issue comes from the user or from the library.
> I am personally facing no issue.

my code:
deno run --allow-net --reload mysql.ts

import { DATA_TYPES, Database, Model } from 'https://deno.land/x/denodb/mod.ts';
console.log(Database);

error: No such file or directory (os error 2)

**Comment by blogwy** [comment] 2020-06-03 05:50
Download https://deno.land/x/denodb/mod.ts
Download https://deno.land/x/denodb/lib/data-types.ts
Download https://deno.land/x/denodb/lib/database.ts
...
Compile file:///Users/wangyu/Desktop/workspace/deno-demo/mysql.ts
error: No such file or directory (os error 2)

**Comment by eveningkid** [comment] 2020-06-03 16:21
Hello again,

I just tried myself and it works all fine. I even tried to reload all the librairies and there is no issue.

Try running (and add all the required `--allow-*` flags):
```
deno run --reload mysql.ts
```

If you are still facing an issue, I will need you to copy the entire `mysql.ts` file here.

Keep in touch

**Comment by eveningkid** [comment] 2020-06-04 08:38
Since there was no follow-up and this seems to be a SQLite/denoDB non-related error, I will close this for now.

Feel free to reopen if the issue persists, and that you are sure the error comes from denoDB.

Thank you!

**Closed by eveningkid** 2020-06-04 08:38 UTC
Labels: question

**Comment by cqthanh** [comment] 2020-06-17 09:12
Don't always add `--reload` flag on every run because `https://deno.land/` has a limit of requests per hour. After you exceed that limit, you will get a 404 error!

**Comment by eveningkid** [comment] 2020-06-17 10:50
Good to mention @cqthanh, it is supposedly only used to get the update you're right :)
